### ISSUE TITLE
[Installation] generated rubocop.yml doesn't cover ruby sources

### ISSUE THREAD

**Issue by nanonull** [strongqa/howitzer#286]
## Meta
Howitzer Version:
2.1.1

## Expected Behavior
.rubocop.yml should include all .rb files by default - coverage starts from all sources and then developers manage exclusion list.
```
AllCops:
  Include:
    - '**/*.rb'
```

## Actual Behavior
.rubocop.yml includes only 2 files, so it is actually ignores all ruby files in project by default.

```
AllCops:
  TargetRubyVersion: 2.3
  Include:
      - Rakefile
      - Gemfile
```

## Steps to reproduce
1. Install howitzer
2. Generate template project for rspec using: `howitzer new <PROJECT NAME> --rspec`
3. Open .rubocop.yml in root of generated project
